In [1]:
import numpy as np

In [3]:
x = np.arange(0,10,2)
y= np.arange(5)

In [4]:
print(x)

[0 2 4 6 8]


In [5]:
print(y)

[0 1 2 3 4]


In [6]:
np.vstack([x,y])

array([[0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4]])

In [7]:
np.hstack([x,y])

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])