Read the requered packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.naive_bayes as sk
%matplotlib inline

Import Data from CSV File. The import takes place in two steps: first reading as pandas and in a second step transform into a numpy matrix/array

In [5]:
data=pd.read_csv('../../../Data/BayesData.csv')
X = data.as_matrix()
Y = X[:,-1]
X = X[:,0:-1]
index_name = data.columns[:-1]

Declare the Gaussian Naive Bayes

In [7]:
nb = sk.GaussianNB()
nb.fit(X,Y)

GaussianNB(priors=None)

Make prediction

In [16]:
x_input = np.array([2,0.05,3]).reshape((1,3))
x_predict = nb.predict(x_input)
print(x_predict)

['yes']


Inspecting the model

In [20]:
print('The classes defined by the model:')
print(nb.classes_)

The classes defined by the model
['no' 'yes']


In [26]:
print('Average Values in the class')
print('---------------------------')
for c,i in zip(nb.classes_,np.arange(0,len(nb.classes_),1)):
    print('Mean value for the data in for class = {k:}'.format(k=c))
    print(nb.theta_[i,:])
print('\nVariance of the attributes in the class')
print('----------------------------------------------------')
for c,i in zip(nb.classes_,np.arange(0,len(nb.classes_),1)):
    print('Variance for the data in for class = {k:}'.format(k=c))
    print(nb.sigma_[i,:])

Average Values in the class
---------------------------
Mean value for the data in for class = no
[ 3.5      0.08625  0.94375]
Mean value for the data in for class = yes
[ 3.          0.05857143  2.35714286]

Variance of the attributes in the class
----------------------------------------------------
Variance for the data in for class = no
[  2.00000000e+00   1.29843970e-03   9.55898440e-01]
Variance for the data in for class = yes
[ 2.28571429  0.00281225  1.40816327]


Probability for a negative age of the company

In [30]:
from scipy.stats import norm

In [37]:
print('Probability to have negative age = {p:0.2f}%'.format(p=100*norm.cdf(0,loc=3.5,scale=2.00)))

Probability to have negative age = 4.01%
